# Generated by Django 6.0.6 on 2026-06-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('invited_by', models.CharField(blank=True, max_length=255)),
                ('follow_up_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('ASSIGNED', 'Assigned'), ('CONNECTED', 'Connected'), ('CONVERTED', 'Converted')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, to='church_groups.department')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_groups.familygroup')),
                ('life_stage_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_groups.lifestagegroup')),
                ('ministries', models.ManyToManyField(blank=True, to='church_groups.ministry')),
            ],
        ),
    ]
