# Generated by Django 6.0.6 on 2026-06-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_groups', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='departments',
            field=models.ManyToManyField(blank=True, to='church_groups.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='family_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_groups.familygroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='life_stage_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_groups.lifestagegroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='ministries',
            field=models.ManyToManyField(blank=True, to='church_groups.ministry'),
        ),
    ]
