# Generated by Django 6.0.6 on 2026-06-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_departments_member_family_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_number',
            field=models.CharField(blank=True, help_text='Generated automatically after membership approval.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
